Usage : ./broady.rb
then wright some messages on the STDIN

Fonctionnalités:

MultiCast : OK
Echange de messages : OK
Récépetion Threadé : OK
Traitement de l'IP perso : OK
Récupération des IP venant des autres émetteurs : OK
Ecriture sur un fichier de conf : OK
Vérification pour éviter les doublon dans le fichier de conf : OK
Ecrit les nouvelle IP sur la sortie standard afin de prévenir le Daemon : OK
DEBUG :

messages a envoyer sur l'entrée standard pour le moment.
